// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WeBZkMbpdWA_o0n-UWpLM4VYfPGboK0',
    appId: '1:1030371866997:web:4190ebb73087f77d8afb3c',
    messagingSenderId: '1030371866997',
    projectId: 'chat-app-62d22',
    authDomain: 'chat-app-62d22.firebaseapp.com',
    storageBucket: 'chat-app-62d22.firebasestorage.app',
    measurementId: 'G-NNDBBCVW10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZTzYi_On1OZepP9bJgPdgG1C5MUsiJQ',
    appId: '1:1030371866997:android:a7e144e3243158b78afb3c',
    messagingSenderId: '1030371866997',
    projectId: 'chat-app-62d22',
    storageBucket: 'chat-app-62d22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFo333JYD2f6GPzViDq_bbm4PwsTkOxBg',
    appId: '1:1030371866997:ios:25e6ce99d32761fb8afb3c',
    messagingSenderId: '1030371866997',
    projectId: 'chat-app-62d22',
    storageBucket: 'chat-app-62d22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
